name: login_app
description: Smart doorbell Flutter app
publish_to: 'none' # this is a local app

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI icons
  cupertino_icons: ^1.0.8

  # Open camera web UI / ESP32 page
  url_launcher: ^6.3.0

  # Formatting dates in history / codes
  intl: ^0.19.0

  # Local "database" on the phone
  shared_preferences: ^2.3.2
  flutter_mjpeg: ^2.0.4
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # If you had assets before, put them here, e.g.:
  # assets:
  #   - assets/
